services:
  engine:
    build: .
    container_name: engine-service
    ports:
      - "${API_PORT}:8088"
    env_file:
      - .env
    networks:
      - snippet-net
volumes:
  db:
  gradle-cache:

networks:
  snippet-net:
    external: true