services:
  engine-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        GITHUB_USER: ${GITHUB_USER}
        GITHUB_TOKEN: ${GITHUB_TOKEN}
    container_name: engine-service
    ports:
      - "${API_PORT}:8089"
    env_file:
      - .env
    networks:
      - snippet-net
volumes:
  db:
  gradle-cache:

networks:
  snippet-net:
    external: true