spring:
  application:
    name: ingsis
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH0_ISSUER_URI}
server:
  port: ${API_PORT:8089}
  address: 0.0.0.0

okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: ${AUTH0_ISSUER_URI}
    # Replace with the API Identifier for your Auth0 API.
    audience: ${AUTH0_AUDIENCE}

bucket:
  url: ${BUCKET_URL}